name = "genesis"
pages_build_output_dir = "." # Esto le dice que tus archivos están en la raíz
compatibility_date = "2024-06-08"

[[d1_databases]]
binding = "db"
database_name = "db"
database_id = "8dbb39ad-2784-445d-a092-5785e7888fb8"

[vars]
SALT_TOKEN = "loiuidjk587468d5448d458d5g8v"
